CREATE TABLE lote (
    codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE sistema (
    codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE demanda (
    codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(80) NOT NULL,
    plataforma VARCHAR(50) NOT NULL,
    tipo_demanda VARCHAR(50) NOT NULL,
    observacao TEXT NOT NULL,
    codigo_lote BIGINT(20) NOT NULL,
    codigo_sistema BIGINT(20) NOT NULL,
    FOREIGN KEY (codigo_lote) REFERENCES lote(codigo),
    FOREIGN KEY (codigo_sistema) REFERENCES sistema(codigo)    
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO sistema VALUES (0, 'SARH');
INSERT INTO sistema VALUES (0, 'FOLHA DE PAGAMENTO');
INSERT INTO sistema VALUES (0, 'SICAM');
INSERT INTO sistema VALUES (0, 'E-AVS');

INSERT INTO lote VALUES (0, 'JANEIRO2018');
INSERT INTO lote VALUES (0, 'FEVEREIRO2018');
INSERT INTO lote VALUES (0, 'MARCO2018');
INSERT INTO lote VALUES (0, 'ABRIL2018');